# Generated by Django 5.0 on 2024-02-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('Roll', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Father_Name', models.CharField(max_length=20)),
                ('Adress', models.TextField()),
            ],
        ),
    ]
