# Generated by Django 5.0 on 2024-02-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('Roll', models.IntegerField(primary_key=True, serialize=False)),
                ('adress', models.TextField()),
            ],
        ),
    ]
